// @flow
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import StoryRouter from 'storybook-router';
import TriggerList from '../Components/TriggerList/TriggerList';

const items = [
    {
        error_value: 25.0,
        sched: {
            endOffset: 1439,
            days: [
                { enabled: true, name: 'Mon' },
                { enabled: true, name: 'Tue' },
                { enabled: true, name: 'Wed' },
                { enabled: true, name: 'Thu' },
                { enabled: true, name: 'Fri' },
                { enabled: true, name: 'Sat' },
                { enabled: true, name: 'Sun' },
            ],
            startOffset: 0,
            tzOffset: -300,
        },
        name: 'Clusterconfig failed responses per minute',
        ttl_state: 'OK',
        id: '05cbc16b-0026-465e-ba26-14883995b63a',
        throttling: 0,
        last_check: {
            timestamp: 1499418163,
            event_timestamp: 1499418163,
            metrics: {
                NotFound: {
                    timestamp: 1495709021,
                    state: 'OK',
                    suppressed: false,
                    event_timestamp: 1495003060,
                    value: 3.0,
                },
                ServiceUnavailable: {
                    timestamp: 1495708481,
                    state: 'OK',
                    suppressed: false,
                    event_timestamp: 1495141059,
                },
                NotImplemented: {
                    timestamp: 1495708481,
                    state: 'OK',
                    suppressed: false,
                    event_timestamp: 1494999279,
                },
            },
            state: 'EXCEPTION',
            score: 100000,
            msg: 'Trigger evaluation exception',
        },
        patterns: ['KE-cloud.clusterconfig.requests.*.code.*'],
        is_simple_trigger: false,
        ttl: 600,
        warn_value: 10.0,
        expression: '',
        targets: [
            "sumSeriesWithWildcards(aliasByNode(exclude(exclude(KE-cloud.clusterconfig.requests.*.code.*, 'OK'), 'NotModified'), 5), 3)",
        ],
        tags: ['clusterconfig', 'KE.Infra.Cloud'],
    },
    {
        error_value: 1000.0,
        sched: {
            endOffset: 1439,
            days: [
                { enabled: true, name: 'Mon' },
                { enabled: true, name: 'Tue' },
                { enabled: true, name: 'Wed' },
                { enabled: true, name: 'Thu' },
                { enabled: true, name: 'Fri' },
                { enabled: true, name: 'Sat' },
                { enabled: true, name: 'Sun' },
            ],
            startOffset: 0,
            tzOffset: -300,
        },
        name: 'KE_SYSTEM_KAMCHATKA_HDD',
        tags: ['KE.System-kamchatka'],
        throttling: 0,
        ttl_state: 'NODATA',
        id: 'e8304401-718e-4a73-8d13-e9abe4c91d69',
        patterns: ['KE.system-kamchatka.allServers.*.volumes.c.freemegabytes'],
        is_simple_trigger: false,
        ttl: 600,
        warn_value: 5000.0,
        last_check: {
            metrics: {
                'KE.system-kamchatka.allServers.k0ch1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-wst.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-keweb1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-exporter.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-index2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-portal1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-rdaemon1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-pservice1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-kladr2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404222,
                },
                'KE.system-kamchatka.allServers.vm-rdaemon2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.k0ch5.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-ke-updater.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-index1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-keweb2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.k0ch3.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-houston-h2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-crypt1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.k0ch4.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-portal2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-kladr1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-fservice2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-pservice2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-afro1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-crypt2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-houston-h1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.k0ch2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-fservice1.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
                'KE.system-kamchatka.allServers.vm-afro2.volumes.c.freemegabytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404940,
                },
            },
            timestamp: 1499418141,
            state: 'OK',
            score: 28000,
        },
        expression: '',
        targets: ['KE.system-kamchatka.allServers.*.volumes.c.freemegabytes'],
        desc:
            '\u041c\u0435\u0441\u0442\u043e \u043d\u0430 \u0434\u0438\u0441\u043a\u0430\u0445 \u043d\u0430 \u041a\u0430\u043c\u0447\u0430\u0442\u0441\u043a\u043e\u0439 \u043f\u043b\u043e\u0449\u0430\u0434\u043a\u0435.',
    },
    {
        error_value: 10.0,
        sched: {
            endOffset: 1439,
            days: [
                { enabled: true, name: 'Mon' },
                { enabled: true, name: 'Tue' },
                { enabled: true, name: 'Wed' },
                { enabled: true, name: 'Thu' },
                { enabled: true, name: 'Fri' },
                { enabled: true, name: 'Sat' },
                { enabled: true, name: 'Sun' },
            ],
            startOffset: 0,
            tzOffset: -300,
        },
        name: 'KE_SYSTEM_KAMCHATKA_RAM',
        tags: ['KE.System-kamchatka'],
        throttling: 0,
        ttl_state: 'NODATA',
        id: '27e9f859-a7b8-4b8e-a07b-360eff754db3',
        patterns: ['KE.system-kamchatka.allServers.*.mem.availablembytes'],
        is_simple_trigger: false,
        ttl: 600,
        warn_value: 512.0,
        last_check: {
            metrics: {
                'KE.system-kamchatka.allServers.k0ch4.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-rdaemon1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-keweb2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-afro2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-portal1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-portal2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-wst.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-kladr1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.k0ch2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-afro1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-rdaemon2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-keweb1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-exporter.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-crypt1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-crypt2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.k0ch5.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-houston-h1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-houston-h2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-pservice2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-fservice1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.k0ch1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-fservice2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-index1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.k0ch3.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-ke-updater.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-index2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-pservice1.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404760,
                },
                'KE.system-kamchatka.allServers.vm-kladr2.mem.availablembytes': {
                    timestamp: 1499417481,
                    state: 'NODATA',
                    suppressed: false,
                    event_timestamp: 1499404103,
                },
            },
            timestamp: 1499418141,
            state: 'OK',
            score: 28000,
        },
        expression: '',
        targets: ['KE.system-kamchatka.allServers.*.mem.availablembytes'],
        desc:
            '\u041f\u0430\u043c\u044f\u0442\u044c \u043d\u0430 \u043f\u043b\u043e\u0449\u0430\u0434\u043a\u0435 \u041a\u043c\u0447\u0430\u0442\u043a\u0438.',
    },
];

storiesOf('TriggersTriggerList', module)
    .addDecorator(StoryRouter())
    .add('default', () => <TriggerList items={items} />);
